version: '3'
services: 
  simulations-manager:
    image: "simulations-manager"
    command: npm run debug
    volumes: 
      - ./dist:/simulations-manager/dist
    ports:
      - "9222:9222"
      - "80:3000"
      - "8000:8000"
    container_name: simulations-manager
    depends_on: 
      - mongodb
    deploy:
      replicas: 1
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports: 
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./../data/db:/data/db:cached
    deploy:
      replicas: 1
  socat:
    image: bobrik/socat:latest
    ports: 
      - "1234:1234"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    command: TCP-LISTEN:1234,fork UNIX-CONNECT:/var/run/docker.sock
    deploy:
      replicas: 1
   
